const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';

const NEW_MESSAGE = 'NEW_MESSAGE';
const START_TYPING = 'START_TYPING';
const STOP_TYPING = 'STOP_TYPING';
const CHANNEL_JOINED = 'CHANNEL_JOINED';
const CHANNEL_LEAVED = 'CHANNEL_LEAVED';
const ONLINE_USERS = 'ONLINE_USERS';
const MEMBER_JOINED = "MEMBER_JOINED"
const MEMBER_LEAVED = "MEMBER_LEAVED"

export {ALERT,REFETCH_CHATS,NEW_MESSAGE,START_TYPING,STOP_TYPING,CHANNEL_JOINED,CHANNEL_LEAVED,ONLINE_USERS,MEMBER_JOINED,MEMBER_LEAVED};